# Site settings
title: Southerneer
email: eric@southerneer.com
description: > # this means to ignore newlines until "baseurl:"
  Southerneer is a technology company dedicated to making things beautifully functional
  things on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://southerneer.com" # the base hostname & protocol for your site
twitter_username: southerneeric
github_username:  southerneer

# Build settings
markdown: kramdown

# Outputting
permalink: /:title.html

destination: website