# Site settings
title: Southerneer
email: eric@southerneer.com
description: > # this means to ignore newlines until "baseurl:"
  Southerneer is a technology company dedicated to making beautifully functional
  things on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:9999" # the base hostname & protocol for your site
twitter_username: iamsoutherneer
github_username:  southerneer
medium_username: southerneer

# Build settings
markdown: kramdown

# Outputting
permalink: /:title.html

source: ./app
destination: ./build

# exclude: [assets/manifest.json, bower.json, bower_components, /lib, /config, Capfile, Gemfile, Gemfile.lock, gulpfile.js, node_modules, notes.txt, package.json]