# Site settings
title: Southerneer
email: eric@southerneer.com
description: > # this means to ignore newlines until "baseurl:"
  Southerneer is a technology company dedicated to making beautifully functional
  things on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://southerneer.com" # the base hostname & protocol for your site
twitter_username: iamsoutherneer
github_username:  southerneer

# Build settings
markdown: kramdown

# Outputting
permalink: /:title.html

destination: website

exclude: [bower.json, Capfile, Gemfile, Gemfile.lock, gulpfile.js, node_modules, notes.txt, package.json]